### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by litian96** [posgraph/coupe.composition-classifier#2]
Can you please provide the pre-trained models somewhere?
Thanks

**Comment by EunbinHong** [comment]
Hi.
You can download pretrained model using following link.
You can get the result using this model with classification_test.lua file.
Thank you for your interest!

http://cg.postech.ac.kr/download/composition-classifier-baseline-epoch-9.net

**Comment by litian96** [comment]
thanks!
